# Generated by Django 4.1.2 on 2022-12-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('booktitle', models.CharField(max_length=500)),
                ('authername', models.CharField(max_length=500)),
                ('currentlycheckedout', models.TextField()),
                ('timescheckedout', models.IntegerField()),
            ],
        ),
    ]
