# Generated by Django 4.1.2 on 2022-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_bookdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='currentlycheckedout',
            field=models.CharField(max_length=500),
        ),
    ]
