# Generated by Django 4.1.2 on 2022-12-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_bookdetails_currentlycheckedout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentfirstname', models.CharField(max_length=100)),
                ('studentlastname', models.CharField(max_length=100)),
                ('booktitle', models.CharField(max_length=500)),
            ],
        ),
    ]
