# Generated by Django 5.0 on 2023-12-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0004_reservationdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookdetails",
            old_name="authername",
            new_name="authorname",
        ),
        migrations.RemoveField(
            model_name="bookdetails",
            name="id",
        ),
        migrations.RemoveField(
            model_name="studentdetails",
            name="id",
        ),
        migrations.AlterField(
            model_name="bookdetails",
            name="bookid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="studentid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
