# Generated by Django 5.0 on 2023-12-12 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0005_rename_authername_bookdetails_authorname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservationdata",
            old_name="studentfirstname",
            new_name="studentname",
        ),
        migrations.RemoveField(
            model_name="reservationdata",
            name="studentlastname",
        ),
    ]
