# Generated by Django 5.0 on 2023-12-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservation",
            "0006_rename_studentfirstname_reservationdata_studentname_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservationdata",
            old_name="studentname",
            new_name="studentfirstname",
        ),
        migrations.AddField(
            model_name="reservationdata",
            name="studentlastname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
